### ISSUE TITLE
Añadir opción de editar memory

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#112]
Hay que añadir la opción de editar memories, están los diseños en el Figma se los podéis pedir a Carlos.

**Comment by Pablocalvo321** [comment]
Siii, se comento con Jose de meterlo como bug para cogerlo cuando se
pudiera.

**Comment by jlerma-onelife** [comment]
Ya está metido como tarea en https://github.com/onelife-social/onelife_app/issues/2304

Cierro esta por duplicada
