### ISSUE TITLE
No reconoce el nombre del grupo 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#122]
V2.9.10 (211)

No me está reconociendo el nombre del grupo. Sale un símbolo de interrogación arriba en vez del nombre.
![IMG_0032](https://github.com/onelife-social/support/assets/161725904/740534df-ea26-44a7-b927-d1e286b5e51a)

![IMG_0031](https://github.com/onelife-social/support/assets/161725904/08a31fb0-3a2a-4759-9782-f8f06f9a7e47)

**Comment by juanan-onelife** [comment]
Solucionado en https://github.com/onelife-social/onelife_app/issues/2422
