### ISSUE TITLE
Notificación cumpleaños triplicada 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#130]
V2.10 (217)

Me están llegando las notificación de cumpleaños 
![IMG_0184](https://github.com/onelife-social/support/assets/161725904/f8d47f4e-3b1c-4d10-a676-da70fbf189e4)
triplicadas.

**Comment by AlbertoJativa** [comment]
Mismo error que https://github.com/onelife-social/support/issues/148
