### ISSUE TITLE
No puede seleccionar fotos, la lleva directo a la camara

### ISSUE THREAD

**Issue by bernidv** [onelife-social/support#134]
Nos llega este MD de una persona que no puede seleccionar fotos de su galeria, al hacerlo , la app la lleva de vuelta a la cámara. Le pasa con distintas fotos indefinidamente, ninguna en especifico. 

https://github.com/onelife-social/support/assets/161715567/3b16f0f7-13db-4a7e-b795-a2a89161a9ef

![WhatsApp Image 2024-05-20 at 10 14 43](https://github.com/onelife-social/support/assets/161715567/93005cd3-3589-4dff-ae2a-6ecc094e3c5f)

**Comment by juanan-onelife** [comment]
![image](https://github.com/onelife-social/support/assets/135533594/7aeca951-a7ad-42fa-bccd-f97a2cd3afbb)

**Comment by AlbertoJativa** [comment]
Mismo error que https://github.com/onelife-social/support/issues/186
