### ISSUE TITLE
No se ordenan las notificaciones 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#139]
V2.11 (219)

Actualizo la home pero no se me ordenan las motivaciones. Antes sí que me salían al menos las que eran de fotos o vídeos pero ahora me pasa tanto con las de chat como las de fotos 

https://github.com/onelife-social/support/assets/161725904/5e99dbbe-c0aa-46c7-95b2-e3b8a0f7c334

**Comment by juanan-onelife** [comment]
Nuevo orden por último evento añadido en la versión 2.11.0+225
