### ISSUE TITLE
No se mueve el curso de la barra de home 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#143]
V2.11.1 (220)

Si pulso sobre el curso de bajo sí que te sale clicada la lupa o la pastilla de home pero si lo hago deslizando con el dedo se queda fijo donde estaba. 

https://github.com/onelife-social/support/assets/161725904/bcdc8fee-c1fe-4899-bdeb-e9cbabd2f9b3

**Comment by juanan-onelife** [comment]
Solucionado en la versión 2.11.0+225
