### ISSUE TITLE
Notificación de unión a grupo repetidas 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#155]
2.11.1 (230)

![IMG_0792](https://github.com/onelife-social/support/assets/161725904/cf517e6a-8881-4b75-ba2b-605d14b01d00)

**Comment by AlbertoJativa** [comment]
Error relacionado con https://github.com/onelife-social/support/issues/148

**Comment by Pablocalvo321** [comment]
Esto si. Que habría que hacerlo en algún momento, cuando alguien se una a un álbum de recuerdo debería aparecerte la notif.
