### ISSUE TITLE
El primer memory se queda congelado 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#162]
# V2.13.1 237

Al subir un memory desde fotos pendientes y ser el primero un vídeo te salta que selecciones un álbum pero al hacerlo se te queda congelado el vídeo y ya no puedes verlo mientras estás subiendo. Se debería de poder visualizar el video mientras se sube y poder subir los demás.

https://github.com/onelife-social/support/assets/161725904/2f3d4cb5-dbcd-4029-944d-6e8727837b6e

**Comment by AlbertoJativa** [comment]
Ya no ocurre... O al menos yo no he logrado reproducirlo

**Comment by AlbertoJativa** [comment]
Prueba y, si no te ocurre, lo cierro... También es verdad que está pendiente implementar la nueva galería...

**Comment by Pablocalvo321** [comment]
Ya no me ocurre! Puedes cerrarlo
