### ISSUE TITLE
Se sale de la app

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#164]
V2.13 Talia sábado 6 a las 9.27

#### Sale de la app de forma inesperada al intentar cargar un vídeo

Entra en la app estando matada y se pone a navegar; a los 3-4 minutos se mete en el grupo “cabró” y al intentar cargar un vídeo le peta y se le sale de la app.

**Comment by AlbertoJativa** [comment]
Se encuentra abierto porque es un error genérico y está linkado a otra tarea...
Se pretende mejorar el rendimiento y reducir los casos globales de cierre inesperado

**Comment by AlexeiOnelife** [comment]
Se cierra la tarea hasta que se notifique de nuevo una issue similar. Se abre issue nueva o se puede reabrir esta misma.
