### ISSUE TITLE
Error en miniatura de la foto en Visualizaciones

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#166]
# V2.13.3 239

Al visualizar alguna foto para ver quién la ha visto me sale con la miniatura error a pesar de que se ha subido correctamente. 

**Aparece icono de error en la miniatura de una foto subida al ver quien la ha visto. Tendría que aparecer la imágen en pequeño**

Parece que le ocurre únicamente al que ha subido la foto, ya que desde otras cuentas se ve bien.

https://github.com/user-attachments/assets/cbbeeec4-8de7-444e-b330-2ced3ee2644a

**Comment by AlbertoJativa** [comment]
Parece estar solucionado, ya no me pasa...

**Comment by Pablocalvo321** [comment]
Por el momento no, estaré atento a ver
