### ISSUE TITLE
No reconoce álbum en el proceso de unión 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#168]
2.13.4 (240)

He entrado a un álbum a través de un QR, leyéndolo desde dots. Al hacerlo me ha salido lo de si quiero subir memories al álbum. Cuando he seleccionado y me he puesto a subir salía que no tenía un álbum seleccionado a pesar de haber sido el proceso desde la unión al álbum.

El problema es que aparece el modal para elegir álbum cuando se debería de subir a ese

https://github.com/user-attachments/assets/96974cf3-9aaa-4a77-aad7-6ffa9d44531b

**Comment by AlbertoJativa** [comment]
He probado y no ocurre.... Cierro

**Comment by Pablocalvo321** [comment]
Esto le paso algo muy parecido a un usuario (Ricki) en una boda, que iba a subir y al llevar poco no se lo reconocía.
