### ISSUE TITLE
Mensaje de error en memory 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#169]
# V2.13.4 240

Me sale un mensaje que parece de la época de Unfiltered y nose bien a qué corresponde.

https://github.com/user-attachments/assets/c8d86d73-1e10-4a51-918c-48ef1faa6189

**Comment by fcabreraOneLife** [comment]
Está relacionada a la tarea https://github.com/onelife-social/onelife_app/issues/2925

**Comment by rubengmlpz** [comment]
Relacionado con https://github.com/onelife-social/onelife_app/issues/3555
