### ISSUE TITLE
Error visión notificaciones 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#18]
Habíamos detectado el error cuando eran 2 notificaciones pero ahora me ha pasado que teniendo 9 se me ha quedado 1 por ver a pesar de haber visto todas las que marcaba.

![IMG_7981](https://github.com/onelife-social/support/assets/161725904/9cbe9970-9e5a-4ec9-968f-268dffa2c0e2)

**Comment by jlerma-onelife** [comment]
Este es el mismo error que #12
