### ISSUE TITLE
No me deja añadir horas posteriores 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#189]
V2.14 241

He ido a crear una etapa nueva pero no me ha dejado poner una fecha posterior a la de fin del evento, debería dejarme crear en cualquier momento entre la fecha de inicio y la de fin por si quiero añadir una etapa nueva a posteriori

![IMG_1481](https://github.com/user-attachments/assets/328468bd-b4b6-4658-b90e-d602c8a9be15)

**Comment by AlbertoJativa** [comment]
Parece estar solucionado...
