### ISSUE TITLE
Me sale una notif pendiente dentro a pesar de no tenerla

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#19]
He entrado en la App y en vez de ver la notif desde fuera me he metido al perfil del álbum, una vez ahí le he dado al vídeo y lo he visto, al volver al perfil del álbum bajo me salía en ver todos los memories como una notif pendiente he entrado y no había nada pero al subir me enviaba para bajo como que sí que había una y al darle me llevaba a la fecha actual que es donde estaba ese memory pero en el dot del calendario no salía como una notif pendiente xq en realidad ya lo había visto 

https://github.com/onelife-social/support/assets/161725904/95422640-97fa-450e-b69a-ceb042df84d4

**Comment by juanan-onelife** [comment]
Parece estar relacionada con la issue https://github.com/onelife-social/onelife_app/issues/2085
