### ISSUE TITLE
Problema en el proceso de subida 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#191]
# V2.14 241

#### Las imágenes se muestran correctamente en el historial tras subirse pero en el álbum muestra error

Parece que hay un problema con las fotos. El proceso de las fotos aparece completo y de repente sale error, le das a "Reintentar" y se vuelve a completar y se puede visualizar desde el historial pero al salir y entrar del álbum vuelve a aparecer el error para reintentar subirla. Así en bucle.

https://github.com/user-attachments/assets/87e54cd1-60c8-4804-867a-ff325f419bc8

Al principio era solo con un par pero ahora son casi todas. El resto de usuarios no pueden ver las fotos, solo los videos.

https://github.com/user-attachments/assets/f96ea774-a87e-4cb9-95ce-11e42bc61740

**Comment by Pablocalvo321** [comment]
Ahora me salen casi todos como error
https://github.com/user-attachments/assets/f96ea774-a87e-4cb9-95ce-11e42bc61740

**Comment by Pablocalvo321** [comment]
Parece que es un problema con las fotos, me he metido a ver con las personas del grupo y no les sale ninguna de las fotos solo los vídeos

**Comment by AlbertoJativa** [comment]
Parece un error con el formato.... Si mencionas que el resto de usuarios no podían ver las fotos, puede ser parecido a lo que ocurría con la extensión .dng

Vamos a comprobarlo

**Comment by AlbertoJativa** [comment]
Si te sigue ocurriendo, puedes mandarme qué album es y alguna descripción de alguna foto en la que ocurra?

**Comment by Pablocalvo321** [comment]
Okey, claro
