### ISSUE TITLE
Límites de fecha 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#193]
V2.14 241

Hay que eliminar los límites de fecha pasada y futura. Yo puedo querer crear un evento para recoger las fotos o vídeos de algo que ya ocurrió o querer programar algo para muchos años 
![IMG_1564](https://github.com/user-attachments/assets/e3fda7a5-7334-47bc-96cf-8b6aad47728d)

**Comment by AlbertoJativa** [comment]
Parece estar solucionado...
