### ISSUE TITLE
No deja cambiar la portada 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#197]
2.14 241

Al darle a cambiar la portada te deja seleccionarla pero luego no te la cambia.

https://github.com/user-attachments/assets/194f707a-4b47-4368-9405-d6fa0c734b7e

**Comment by Pablocalvo321** [comment]
Parece que deja en los álbumes de evento pero en los de recuerdos

**Comment by juanan-onelife** [comment]
Solucionado versión 2.14.2 243
