### ISSUE TITLE
No reconoce los días pasados en los que he entrado en la apo

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#20]
Me sale que voy por el día 1 de 10 por lo que no puedo superar el nivel 4, ahora mismo yo no podría subir ningún memory hasta dentro de 9 días y tampoco podré xq me pedirá que lleve 20 días 

https://github.com/onelife-social/support/assets/161725904/e085c413-5c5a-464f-81d1-11dcb73e009f

**Comment by juanan-onelife** [comment]
Los usuarios que estaban registrados en la app antes de implementar los niveles, se actualizaron todos a nivel 5 para no tener este problema con el número de días que habían entrado en la app.
