### ISSUE TITLE
Tira de la app

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#200]
V2.14

Le saca de la app al usuario nataliacalvoc entre las 20.46 y 20.53 Del sábado 27

**Comment by AlbertoJativa** [comment]
Lo podemos dar por cerrado?

**Comment by Pablocalvo321** [comment]
Puedes darlo pero el error de que tira de la app sigue ahí, igual sino hay que crear una tarea más grande respecto a este tema. Yo puse el ejemplo por si servia para identificar el problema en la base de errores.

**Comment by AlbertoJativa** [comment]
Deberíamos de mirar la lista de prioridades y tener en cuenta estas cosas...
Cierre inesperado de la app, Problemas en la subida de memories, visualización de memories, temas de rendimiento en baja cobertura, optimización del hardware de los dispositivos (sobretodo android)...
El problema está en que van saliendo nuevas funcionalidades como las alertas, la monetización... que son más importantes y esto se queda siempre atrás

**Comment by Pablocalvo321** [comment]
Coméntalo con Jose para crear tareas con la máxima info posible de estos casos de calidad que sabemos que ocurren constantemente y se nos están acumulando para que en cuanto podamos cogerlos sean más fáciles de solucionar por tener la máxima información recogida posible.
