### ISSUE TITLE
Error chat 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#204]
2.14.8 252

Me salen mensajes pendientes pero cuando clico para ir a donde se supone que están no me lleva al Lugar correcto y hace que resulte muy complejo seguir la conversación o donde se supone que quedan mensajes por leer.

https://github.com/user-attachments/assets/cdd581d4-f382-4d7d-a9ab-cb7b80011fb2

**Comment by AlbertoJativa** [comment]
Ocurre en:
- https://github.com/onelife-social/support/issues/132
