### ISSUE TITLE
Se raya al Estsr en visión galería 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#209]
V2.14.8 252

He ido a buscar una foto de febrero de 2023, he pulsado el mes de febrero y al seguir subiendo para encontrar la foto por que era a principios de mes se ha empezado a rayar y me iba moviendo entre los meses sin sentido, haciendo imposible llegar a la foto en concreto. Solo me ha dejado llegar a la foto en cuestión si iba haciendo scroll de manera manual y no pulsando en el mes.

https://github.com/user-attachments/assets/e79aaadc-7ecd-440c-acf4-35a4038de086

**Comment by AlbertoJativa** [comment]
No me pasa... ¿Te ha vuelto a pasar?

**Comment by Pablocalvo321** [comment]
No..
