### ISSUE TITLE
Error subida vídeo 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#215]
V2.15 255

He ido a subir 10 archivos (4 vídeos 0:03,0:13,0:43 y 0:25) al darle a subir lo primero que me ha dicho es el
Pop up de vídeo demasiado corto (lo cual es raro xq ninguno de los vídeos es de menos de un segundo) le he dado a descargar y me ha salido el archivo 2 pero estaba la pantalla en negro, le he dado a subir igualmente y en el tercero al ver que seguía en negro le he dado a atrás al hacerlo me ha hecho un loop súper raro, me ha llevado a la vista de perfil de álbum y estaba como con franjas cortando la visión del álbum. Luego me ha llevado a la visión de galería donde se veía el vídeo subiéndose y otro con el botón de reintentar. Luego ya he empezado a grabar el vídeo y la visión era que estaba el vídeo intentadose subir pero no se subía y se me han quedado los archivos en azul sin dejar ver, ni borrar ni hacer nada con ellos. He subido 5 fotos que me ha dejado aunque iba un poco lagueado y se me han subido dejando estos archivos con error bajo. 

https://github.com/user-attachments/assets/b43217ae-c297-4415-938a-2101ba254589

**Comment by rubengmlpz** [comment]
Por lo que parece fue un error puntual del servidor de AWS. En el entorno de develop este está caído y el error se reproduce para todos los vídeos subidos, mientras que en producción funciona correctamente de momento. Notificar si vuelve a ocurrir este error.

**Comment by AlbertoJativa** [comment]
En qué estado está?
