### ISSUE TITLE
Crear opción de borrar desde historial 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#216]
V2.15 255

ocurre bastante que algún vídeo se queda colgado o hay algún error. Creo que si en el historial pusiéramos una opción de borrar sería cómodo para que en esos casos lo quites de ahí y no se quede ensuciando el álbum.

https://www.figma.com/design/suputCXz7s2rUd1BMg7kOt/OneLife?node-id=23350-39685&t=SszW4bzdLB0ChTLA-1

**Comment by AlbertoJativa** [comment]
Creo tarea y lo muevo al proyecto
