### ISSUE TITLE
Las fotos no se separan por etapa de planning en album de eventos

### ISSUE THREAD

**Issue by bernidv** [onelife-social/support#218]
Aunque suba distintas foto a cada etapa, al momento de entrar en una salen todas mezcladas y si hago scroll, arriba el titulo no cambia a medida que pasan las etapas. Han llegado mds de esto a insta

https://github.com/user-attachments/assets/3a9a6f29-75a5-480a-a59a-4f78bed18e70

**Comment by AlbertoJativa** [comment]
Lo cierro porque se va a implementar la nueva versión con el filtro, los títulos y duraciones...
