### ISSUE TITLE
Lentitud al entrar 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#224]
2.15 255

Ya me ha pasado un par de veces que al entrar en la app después de estar unas horas sin acceder me sale el círculo de cargando cuando eso no me había pasado nunca (el lado positivo es que parece que hace como una carga y entonces las notificaciones pendientes de ver que tenía me salen cuando antes no me salían hasta pasado un tiempo)

https://github.com/user-attachments/assets/fabb5559-0721-4939-8b9e-a7b44ade03f8

**Comment by AlbertoJativa** [comment]
Creo que se habló en algún momento y era porque nos traíamos todas los memories pendientes
No se si se llegó a solucionar...

**Comment by Pablocalvo321** [comment]
A mi no me ha vuelto a pasar.
