### ISSUE TITLE
Al darle a las fotos sale este mensaje

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#228]
V2.14.13

Estaba viendo archivos con normalidad de galería y al entrar en las fotos me salía el mensaje de error al cargar el memory. Lo raro es que solo pasaba en las fotos y en las que había subido yo. 

https://github.com/user-attachments/assets/94943991-e537-4bb9-9979-c500ad775b65

**Comment by AlbertoJativa** [comment]
No consigo reproducirlo ni una sola vez... ¿Cuándo te pasa?

**Comment by Pablocalvo321** [comment]
Este es el mismo que te he dicho que me ha pasado dos veces en domingo.
Jose también me comento que le había pasado, igual el te puede dar más
pistas.

**Comment by rubengmlpz** [comment]
https://github.com/onelife-social/onelife_app/issues/3555

Relacionado
