### ISSUE TITLE
Cree que he adquirido algo que no he hecho

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#236]
V2.16

He intentando hacer un pago y me ha dado error, luego al intentar subir las personas me estaba saliendo el mensaje de que se descontarán las 20 personas que ya he pagado pero esa info no es real xq yo no he pagado x nada ya que me ha dado error. 
![IMG_3018](https://github.com/user-attachments/assets/223807d7-2019-4e96-ac9f-5a119f4b2a75)

**Comment by AlbertoJativa** [comment]
Es un error del label, el precio sí que se calcula bien

**Comment by Pablocalvo321** [comment]
He visto que aunque no haya dado a pagar pasa igual

**Comment by AlbertoJativa** [comment]
Lo he hablado con Juanan y de momento, de la forma en la que está hecho, no se puede controlar...
