### ISSUE TITLE
Al ver una notificación me deja ver una pero la otra sale en negro 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#24]
Tenía 2 notif en un grupo y al darle me salía en negro pero ni siquiera estaba como de costumbre el símbolo de cargando, al pasar a la siguiente si que me dejaba ver la otra notif y al entrar en el álbum me dejaba ver la que salía en negro 

https://github.com/onelife-social/support/assets/161725904/6c4f4f68-e457-41c4-8e4d-5e6c4b17bd7e

**Comment by juanan-onelife** [comment]
Relacionada con https://github.com/onelife-social/support/issues/50

**Comment by AlbertoJativa** [comment]
Sigue ocurriendo? Parece un bug muy antiguo

**Comment by Pablocalvo321** [comment]
Buenas!

No me sigue pasando.
