### ISSUE TITLE
Planing 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#250]
2.16 269

cuando estoy en la parte de planing y clico en cualquier parte de la etapa debería bajarme el desplegable y lo mismo para guardarlo. 
![IMG_3147](https://github.com/user-attachments/assets/4f436573-693e-479f-9016-a603fb58d098)

**Comment by AlbertoJativa** [comment]
Duplicada en https://github.com/onelife-social/onelife_app/issues/3618
