### ISSUE TITLE
Error en proceso de subida 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#26]
Hay 2 errores aquí 

1. La barra de progreso avanza y luego retrocede (no he podido grabarlo perfecto pero al principio se llega a apreciar)
2. ⁠al estar subiendo en un segundo grupo ha petado y no me dejaba ir a todos los memories, además de que no me cargaba el perfil del álbum

https://github.com/onelife-social/support/assets/161725904/b14b8ae8-df37-4ed9-931b-89e065456a24

**Comment by juanan-onelife** [comment]
La barra de progreso y la subida está solucionado en la última versión.
