### ISSUE TITLE
Error web subida vídeo 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#269]
Safari iOS prod 

Al subir el vídeo se sube correctamente pero no carga la miniatura de portada ni en historial ni en la galería. 

https://github.com/user-attachments/assets/32e83c9a-2f20-460a-9281-9b366b916729

**Comment by jlerma-onelife** [comment]
El vídeo no se corresponde con el texto.

Con respecto a la descripción:
```
Al subir el vídeo se sube correctamente pero no carga la miniatura de portada ni en historial ni en la galería.
```
Eso es así, en la web no podemos capturar la primera imagen del vídeo para mostrar la miniatura.

Con respecto al vídeo, parece que algo se queda cargando, pero no sé donde has pulsado para llegar hasta ahí.

**Comment by jlerma-onelife** [comment]
El vídeo veo que es el mismo que el de la issue #268

Cierro esta entonces porque lo de no cargar la minuatura en vídeos hasta que se recarga la página es algo que por ahora tenemos que asumir.

**Comment by Pablocalvo321** [comment]
Y no podríamos traernos una imagen nuestra? Royo un tick de subido cuando
ya este ok hasta que traiga la miniatura.
