### ISSUE TITLE
Lector QR no funciona

### ISSUE THREAD

**Issue by bernidv** [onelife-social/support#32]
07/03/2024 hola me he descargado la app y lo tengo todo hecho pero al descargar el QR no me lo lee. Como puedo hacerlo? es que me caso en un mes y me gustaria hacerlo en las mesas. No me lo lee ningun movil.
*Usaa el lector de Qr que viene con el movil, un Xiaomi Redmi Note 11

**Comment by juanan-onelife** [comment]
relacionada con https://github.com/onelife-social/onelife_app/issues/1989
