### ISSUE TITLE
No carga el calendario

### ISSUE THREAD

**Issue by bernidv** [onelife-social/support#34]
Subi fotos a un album y no me salen en el movil de empresa, me sale el calendario vacio. Si entro del personal si se ven

https://github.com/onelife-social/support/assets/161715567/998c06a1-c49d-4a4b-b674-f78d171aa56c

![IMG_7254](https://github.com/onelife-social/support/assets/161715567/64ef1bce-111d-4f46-a4e9-3f2753dbb94a)

https://github.com/onelife-social/support/assets/161715567/dd8f7476-6ad4-4d4e-a7ca-d78092bdeb3b

**Comment by juanan-onelife** [comment]
Revisar si sigue ocurriendo en la version  2.7.5+180
