### ISSUE TITLE
Se le guardan las fotos al revés 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#37]
Al usuario Edir y Veravonstein en el grupo de abuelita se le muestran las fotos al revés, la foto la ha subido Talia y a ella se le ve normal. 
![48b06890-5223-4f31-83e4-5665b6844e5a](https://github.com/onelife-social/support/assets/161725904/18bd2038-046d-4223-aa92-bbfa5197eef4)
![94dd74d5-8979-4b7e-85b4-002b1deb6641](https://github.com/onelife-social/support/assets/161725904/61e66c32-3f8d-45dd-8350-657ef0ff976d)

**Comment by jlerma-onelife** [comment]
Necesitamos algo más de info de esta issue para intentar localizarla:

- ¿Le pasa solamente a esos usuarios y en ese grupo? 
- ¿A otros usuarios del grupo se les visualiza bien? 
- ¿Sabemos que versión de la app y que móvil tienen?
- ¿Podríamos subir alguna de esas fotos a un grupo del que nos paséis enlace para unirnos y así hacer pruebas con distintos dispositivos?

**Comment by jlerma-onelife** [comment]
@Pablocalvo321 puedes mirar las preguntas del comentario anterior porfa. Me comenta @juanan-onelife que no consigue reproducirlo

**Comment by Pablocalvo321** [comment]
Buenas!!

Me lo apunto como pendiente para intentar recabar esa información por que
tenia que estar Talia con su familia, lo antes posible os lo envio.

**Comment by AlbertoJativa** [comment]
Ha vuelto a ocurrir?

**Comment by Pablocalvo321** [comment]
Buenas!

No me lo han vuelto a reportar.
