### ISSUE TITLE
El SMS del tlf te llega con un nombre 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#42]
Estaba haciendo una prueba en el registro y me he dado cuenta que el SMS de verificación me lo ha enviado como si me lo hubieran enviado un contacto de mi agenda. Muy raro 
![IMG_8230](https://github.com/onelife-social/support/assets/161725904/0461d6eb-5f5a-4192-852f-f58fdb23590b)

**Comment by juanan-onelife** [comment]
Los números de teléfono que envían el SMS son únicos de Firebase.
