### ISSUE TITLE
No deja ver memory 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#49]
Tenía notif de un memory pendiente y me meto pero no me deja verlo, se queda eternamente cargando. Si voy a verlo desde el perfil me deja ver el de antes y el de después pero no ese.

https://github.com/onelife-social/support/assets/161725904/0dae0a9f-cde8-4fdb-906a-311c591598b3

**Comment by juanan-onelife** [comment]
Tiene pinta estar relacionada con https://github.com/onelife-social/support/issues/50
