### ISSUE TITLE
Problema al acceder al historial

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#5]
Cuando se meten Angels y Maria en el historial les empeiza a parpadear y no les permite seguir usando la App 

Le sucede a esta usuaria. Ver error en Crashalytics
HYCqnJ7I8FS1bNRjO8sZPcw9h8D3

Lo ha reproducido el día 29 de febrero a las 19.03h

**Comment by juanan-onelife** [comment]
Mismo error que en https://github.com/onelife-social/support/issues/6
