### ISSUE TITLE
Mensaje de error en la subida 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#53]
Aquí hay que ver o bien de encontrar una vía en la que al reintentar se solucione y te deje subirlo o que el mensaje no te salga cada vez que entras. Sería poner un máximo de una vez de error en la subida y una vez visto que sobre el mismo vídeo no te esté saliendo cada vez.
![IMG_8370](https://github.com/onelife-social/support/assets/161725904/09f6d1e7-776d-4b70-b3bc-05ad2848eced)

**Comment by juanan-onelife** [comment]
Probar si el reintento del video está solucionado en la versión 2.7.2+176

**Comment by Pablocalvo321** [comment]
Perfecto!! Con esta versión ya te lo sube, igualmente habría que limitar el
número de veces que sale el mensaje. Como tope pondría que te aparezca 2
veces.

Un saludo,
