### ISSUE TITLE
No es clickable el link 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#54]
Me ha llegado una invitación a un grupo pero el link no es clickable. 
![IMG_8372](https://github.com/onelife-social/support/assets/161725904/1c488e76-508a-4d96-bc3e-77bfe9c6a442)

**Comment by juanan-onelife** [comment]
El texto con el enlace que se genera desde la app tiene el formato correcto tanto en Android como en iOS. El ejemplo que nos pasas es un poco raro, porque parece que se ha enviado en dos partes. Tiene pinta que no es clickable porque se ha introducido un salto de linea en el texto y la app de iMessage no lo reconoce como enlace.

![image](https:
![Simulator Screenshot - iPhone 15 - 2024-03-20 at 15 54 48](https://github.com/onelife-social/support/assets/135533594/57b4df79-584c-45fe-8502-12b98d1d4a6f)
//github.com/onelife-social/support/assets/135533594/0b2bf3bf-b31f-4daa-b7ee-b01e94111b95)
