### ISSUE TITLE
Parpadeos muy extraños al subir muchos archivos 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#80]
V2.8 

he probado a subir bastantes archivos a la vez y ha empezado a hacer unos parpadeos muy raros con dos fotos en concreto. Finalmente se han cargado y ha enseñado la miniatura.

https://github.com/onelife-social/support/assets/161725904/03a91209-c53c-4ff5-b93e-506c4591f411

https://github.com/onelife-social/support/assets/161725904/5a7f82e8-08ee-4fde-9499-f9abfd4006ad

**Comment by jlerma-onelife** [comment]
En realidad eso no es un error. Es el comportamiento. Cada vez que se publica una memory, se actualiza en esa pantalla. Por eso al subir muchas te van apareciendo conforme se van publicando.

**Comment by Pablocalvo321** [comment]
quieres decir que el parpadeo que hace la pantalla donde sale la
exclamación es una especie de refresh que hace cada vez que se sube un
memory?

**Comment by jlerma-onelife** [comment]
Cierro issue, esto se trata en esta historia https://github.com/onelife-social/onelife_app/issues/2201
