### ISSUE TITLE
Miembros erróneos chat 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#81]
V2.8

en el chat aparece que hay 23 miembros pero en realidad hay 16

https://github.com/onelife-social/support/assets/161725904/ebe313d1-13b3-44c9-80fe-0e79dd3c8f28

**Comment by AlexeiOnelife** [comment]
Investigando hemos averiguado que esto se debe a que el sistema de chat es único, mientras que nosotros tenemos los servidores de DEV / PROD, con sus usuarios de test registrados, que son los que están en el grupo de errores. Por tanto, este error sólo se da en los grupos de testeo (y sabemos por qué) y no para los usuarios
