### ISSUE TITLE
Error caché notif 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#84]
V2.8

Me han ocurrido dos errores.

1.Tenia 2 notif en un grupo y al darle me ha dejado ver 1 pero no la otra (lo que pasaba antes y se suponía que ya no ocurría)

2. Tenía una notif de chat he entrado para verla y al salir seguía teniendo la notif de chat, a los segundos ha desaparecido sola. Además me salía como que eran 2 mensajes cuando en realidad eran 3

https://github.com/onelife-social/support/assets/161725904/19ca8017-a00c-4c9d-8a4c-2b4e5f35ac16

**Comment by jlerma-onelife** [comment]
Esto se está tratando en la https://github.com/onelife-social/onelife_app/issues/2085
