### ISSUE TITLE
Chats desordenados a partir de 30 grupos 

### ISSUE THREAD

**Issue by Pablocalvo321** [onelife-social/support#9]
Los chats se me van al último lugar y los grupos no se me están ordenando por orden de última notificación, parece que ha habido algo que está afectando al orden de los grupos

![IMG_7876](https://github.com/onelife-social/support/assets/161725904/7af79e7a-73cf-4965-b709-72449f978dc8)

**Comment by juanan-onelife** [comment]
No es posible de reproducir, revisar si sigue sucediendo en la última versión.
